--[[
    init.lua
    Created: 05/09/2024 16:31:33
    Description: Autogenerated script file for the map shady_shop.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local shady_shop = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---shady_shop.Init(zone)
--Engine callback function
function shady_shop.Init(zone)


end

---shady_shop.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function shady_shop.EnterSegment(zone, rescuing, segmentID, mapID)


end

---shady_shop.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function shady_shop.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---shady_shop.Rescued(zone, name, mail)
--Engine callback function
function shady_shop.Rescued(zone, name, mail)


end

return shady_shop

